"""Tests for the `pipeline` module.

Use 'pytest tests/test_pipeline.py::test_name' to run a single test.

Use 'make test' to run all tests.

TODO: Do not check every parameter combination for all tests.
"""

import json
import os


def test_prompt(data_paths_fixture, config) -> None:
    """Test the prompt generated by build_dataset."""
    # Get the puzzle path
    puzzle_path = data_paths_fixture[0]

    # Load the first file in the puzzle directory
    puzzle_filename = os.listdir(puzzle_path)[0]
    puzzle_file_path_str = puzzle_path / puzzle_filename

    # Load a generated puzzle
    with open(puzzle_file_path_str, "r") as f:
        prompt = f.read()

    prompt_templates = config.language.prompt_templates

    # Check if the prompt is a string and has a length greater than the first template
    assert isinstance(prompt, str)
    assert len(prompt) > len(prompt_templates[0])


def test_solution(data_paths_fixture, config) -> None:
    """Test the solutions generated by build_dataset."""
    # Get the solution path
    solution_path = data_paths_fixture[1]

    # Load a generated solution
    solution_file_path = solution_path / "zebra_puzzle_0_solution.json"
    with open(solution_file_path, "r") as f:
        solution = f.read()

    # Check the dimensions of the solution
    solution_dict = json.loads(solution)
    assert isinstance(solution_dict, dict)
    assert len(solution_dict) == config.n_objects
    assert len(solution_dict["object_1"]) == config.n_attributes


def test_red_herring_files(data_paths_fixture, config) -> None:
    """Test the red herring files generated by build_dataset."""
    # Get the red herring path
    red_herring_path = data_paths_fixture[2]

    # Load a generated red herring file
    red_herring_file_path = red_herring_path / "zebra_puzzle_0_red_herrings.txt"
    with open(red_herring_file_path, "r") as f:
        red_herring_indices_str = f.read()

    # Check that the file is empty or contains comma-separated indices
    assert red_herring_indices_str == "" or isinstance(red_herring_indices_str, str)

    # If the file is not empty, check that it contains comma-separated indices
    # and that the number of indices matches n_red_herring_clues
    # and that the maximum index is greater than or equal to n_red_herring_clues
    if red_herring_indices_str != "":
        red_herring_indices_list = red_herring_indices_str.split(",")
        i_red_herrings = [int(i) for i in red_herring_indices_list]
        assert isinstance(i_red_herrings, list)
        assert len(i_red_herrings) == config.n_red_herring_clues
        assert max(i_red_herrings) >= config.n_red_herring_clues
