# Config file for generating zebra puzzles in Faroese with the classic "houses" theme.

# TODO: After 'fyri'/'millum' comes accusative
#       After 'av' comes dative
#       After 'við' comes ?
#       Use accusative and dative, generally, when relevant
#       Not important: When a list of words are all masculine, use 'teir' instead of 'tey'


# Theme
theme: fo_hus

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# The attributes below should be in the preferred order of categories in the clues.

attributes:

    tjóðskapir:
        Danmark: ['danin', 'er dani', 'er ikki dani']
        Svøríki: ['svenskarin', 'er svenskur', 'er ikki svenskur']
        Lettland: ['lettin', 'er lettiskur', 'er ikki lettiskur']
        Frakland: ['fraklendingurin', 'er franskur', 'er ikki franskur']
        Spania: ['spaniólin', 'er spanskur', 'er ikki spanskur']
        Italia: ['italiumaðurin', 'er italskur', 'er ikki italskur']
        Noreg: ['norðmaðurin', 'er norskur', 'er ikki norskur']
        Føroyar: ['føroyingurin', 'er føroyskur', 'er ikki føroyskur']
        Niðurlond: ['hollendingurin', 'er hollendskur', 'er ikki hollendskur']
        Ísland: ['íslendingurin', 'er íslendskur', 'er ikki íslendskur']
        Bretland: ['bretin', 'er bretskur', 'er ikki bretskur']

    arbeiði:
        bakari: ['bakarin', 'er bakari', 'er ikki bakari']
        kirkjutænari: ['kirkjutænarin', 'er kirkjutænari', 'er ikki kirkjutænari']
        løgreglumaður: ['løgreglumaðurin', 'er løgreglumaður', 'er ikki løgreglumaður']
        sjúkrasystir: ['sjúkrasysturin', 'er sjúkrasystir', 'er ikki sjúkrasystir']
        lærari: ['lærarin', 'er lærari', 'er ikki lærari']
        ritbúnaðarverkfrøðingur: ['ritbúnaðarverkfrøðingurin', 'er ritbúnaðarverkfrøðingur', 'er ikki ritbúnaðarverkfrøðingur']
        handilshjálpari: ['handilshjálparin', 'er handilshjálpari', 'er ikki handilshjálpari']

    kelidjór:
        ketta: ['kettueigarin', 'eigur kettu', 'eigur ikki kettu']
        hundur: ['hundaeigarin', 'eigur hund', 'eigur ikki hund']
        kanin: ['kanineigarin', 'eigur kanin', 'eigur ikki kanin']
        sebra: ['sebraeigarin', 'eigur sebra', 'eigur ikki sebra']
        undulát: ['unduláteigarin', 'eigur undulát', 'eigur ikki undulát']
        snigil: ['snigileigarin', 'eigur snigil', 'eigur ikki snigil']
        reikandi kvistur: ['eigarin av einum reikandi kvisti', 'eigur reikandi kvistur', 'eigur ikki reikandi kvistur']

    drikkur:
        djús: ['djúsdrekkarin', 'drekkur djús', 'drekkur ikki djús']
        kaffi: ['kaffidrekkarin', 'drekkur kaffi', 'drekkur ikki kaffi']
        mjólk: ['mjólkadrekkarin', 'drekkur mjólk', 'drekkur ikki mjólk']
        smoothie: ['smoothiedrekkarin', 'drekkur smoothie', 'drekkur ikki smoothie']
        kakao: ['kakaodrekkarin', 'drekkur kakao', 'drekkur ikki kakao']
        te: ['tedrekkarin', 'drekkur te', 'drekkur ikki te']
        sodavatn: ['sodavatnsdrekkarin', 'drekkur sodavatn', 'drekkur ikki sodavatn']

    yndisbókasjangrur:
        yrkisbókmentir: ['yrkisbókmentalesarin', 'lesur yrkisbókmentir', 'lesur ikki yrkisbókmentir']
        brotsskaldsøgu: ['brotsskaldsøgulskarin', 'lesur brotsskaldsøgu', 'lesur ikki brotsskaldsøgu']
        fantasi: ['fantasilesarin', 'lesur fantasi', 'lesur ikki fantasi']
        vísindaskaldsøgur: ['vísindaskaldsøgulesarin', 'lesur vísindaskaldsøgu', 'lesur ikki vísindaskaldsøgu']
        ræðuskaldsøgur: ['ræðuskaldsøgulesarin', 'lesur ræðuskaldsøgu', 'lesur ikki ræðuskaldsøgu']
        yrkingar: ['yrkingalesarin', 'lesur yrkingar', 'lesur ikki yrkingar']
        romantiskar skaldsøgur: ['persónurin, sum lesur romantiskar skaldsøgu', 'lesur romantiskar skaldsøgu', 'lesur ikki romantiskar skaldsøgu']

    frítíðarítriv:
        klintring: ['persónurin, sum klintrar', 'klintrar', 'klintrar ikki']
        máling: ['persónurin, sum málar', 'málar', 'málar ikki']
        borðspøl: ['persónurin, sum spælir borðspøl', 'spælir borðspøl', 'spælir ikki borðspøl']
        tennis: ['persónurin, sum spælir tennis', 'spælir tennis', 'spælir ikki tennis']
        hekla: ['persónurin, sum heklar', 'heklar', 'heklar ikki']
        fóbóltur: ['persónurin, sum spælir fótbólt', 'spælir fótbólt', 'spælir ikki fótbólt']
        hondbóltur: ['persónurin, sum spælir hondbólt', 'spælir hondbólt', 'spælir ikki hondbólt']

    yndisfruktir:
        súrepli: ['persónurin, sum elskar súrepli', 'elskar súrepli', 'dámar ikki súrepli']
        pera: ['persónurin, sum elskar perur', 'elskar perur', 'dámar ikki perur']
        appilsin: ['persónurin, sum elskar appelsinir', 'elskar appelsinir', 'dámar ikki appelsinir']
        banan: ['persónurin, sum elskar bananir', 'elskar bananir', 'dámar ikki bananir']
        jarðber: ['persónurin, sum elskar jarðber', 'elskar jarðber', 'dámar ikki jarðber']
        sólber: ['persónurin, sum elskar sólber', 'elskar sólber', 'dámar ikki sólber']
        skógarjarðber: ['persónurin, sum elskar skógarjarðber', 'elskar skógarjarðber', 'dámar ikki skógarjarðber']

# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues.
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: "{attribute_desc} býr í húsi nummar {i_object}."
    not_at: "{attribute_desc} býr ikki í húsi nummar {i_object}."
    next_to: "{attribute_desc_1} býr við síðuna av {attribute_desc_2}."
    not_next_to: "{attribute_desc_1} býr ikki við síðuna av {attribute_desc_2}, og tey eru ikki sami persónur."
    just_left_of: "{attribute_desc_1} býr beint til vinstru fyri {attribute_desc_2}."
    just_right_of: "{attribute_desc_1} býr beint til høgru fyri {attribute_desc_2}."
    left_of: "{attribute_desc_1} býr til vinstru fyri {attribute_desc_2}."
    right_of: "{attribute_desc_1} býr til høgru fyri {attribute_desc_2}."
    same_object: "{attribute_desc_1} {attribute_desc_2}."
    not_same_object: "{attribute_desc_1} {attribute_desc_2}."
    between: "{attribute_desc_2} býr millum {attribute_desc_1} og {attribute_desc_3}."
    not_between: "{attribute_desc_1} býr ikki millum {attribute_desc_2} og {attribute_desc_3}, og tey eru trý ymisk fólk."
    multiple_between: "{attribute_desc_1} og {attribute_desc_2} búgva við {n_between} húsum ímillum sín."
    one_between: "Tað eru eini hús millum {attribute_desc_1} og {attribute_desc_2}."

# Prompt
# We use two different prompt templates depending on whether we have multiple attributes in each category or just one.
# prompt_and is the word used for separating the last two attributes in a list of attributes.

prompt_and: og

prompt_templates:
    - |
        Ein røð av húsum eru talmerkt frá 1 til {n_objects} frá vinstru til høgru.

        Í hvørjum einastu húsum býr ein persónur, sum hevur ein einstakan eginleika úr hvørjum einasta flokki, sum stendur niðanfyri: 

        {chosen_attributes_str}

        Harumframt vita vit fylgjandi:

        {chosen_clues_str}

        Hvør hevur hvørjar eginleikar og býr í hvørjum húsum?

        Vinarliga gev títt svar sum JSON dictionary í sniðinum niðanfyri. Hvør røð skal byrja við object_X har X er húsanummarið. Hvør teigur umboðar ein flokk, og teir skulu vera í somu raðfylgju, sum flokkarnir ið eru nevndir omanfyri.

        {solution_template}
    - |
        Ein røð av húsum eru talmerkt frá 1 til {n_objects} frá vinstru til høgru.

        Í hvørjum húsum býr ein persónur við einum einstøkum eginleika í flokkinum {chosen_attributes_str}.

        Harumframt vita vit fylgjandi:

        {chosen_clues_str}

        Hvør hevur hvørjar eginleikar og býr í hvørjum húsi?

        Vinarliga gev títt svar sum JSON orðabók í sniðinum niðanfyri. Hvør røð skal byrja við object_X har X er húsanummarið. Aftaná kemur ein teigur við eginleikunum í áðurnevnda flokki.

        {solution_template}

# Red herrings
# The red herring attributes that are not used in the main clues, but are included in the prompt to make the puzzle more challenging.
# NOTE: More types could be added such as "The person with a cactus is not the baker"

red_herring_clues_dict:
    same_herring: "{attribute_desc} {attribute_desc_herring}."
    next_to_herring: "{attribute_desc} býr við síðuna av {attribute_desc_herring}."
    double_herring: "{attribute_desc_herring_1} og {attribute_desc_herring_2}."
    fact: "{fact}."
    object_fact: "{attribute_desc} veit, at {fact}."
    friends: "{attribute_desc} er góður vinur við {attribute_desc_herring}."
    herring_found_at: "{attribute_desc_herring} býr í húsi nummar {i_object}."
    herring_not_at: "{attribute_desc_herring} býr ikki í húsi nummar {i_object}."

red_herring_attributes:
    reytt hár: ['persónurin við reyðum hári','hevur reytt hár']
    brillur: ['persónurin við brillum','brúkar brillur']
    tatovering: ['persónurin við tatovering','hevur eina tatovering']
    gittar: ['persónurin, sum spælir gittar','spælir gittar']
    súkkla: ['persónurin við súkklu','hevur súkklu']
    marsvín: ['persónurin við einum marsvíni','hevur eitt marsvín']
    kaktus: ['persónurin, sum ikki eigur ein kaktus','eigur ikki ein kaktus']
    telduspæl: ['persónurin, sum spælir telduspøl','spælir telduspøl']
    systir: ['persónurin við einari systur','hevur eina systur']
    mango: ['persónurin, sum heldur, at næstbesta fruktin er mango','heldur, at tann næstbesta fruktin er mango']
    siglur: ['persónurin, sum ofta siglir','siglir ofta']
    Kanada: ['persónurin, sum hevur verið í Kanada','hevur verið í Kanada']
    støddfrøði: ['persónurin, sum hevur masterútbúgving í støddfrøði','hevur masterútbúgving í støddfrøði']
    alisfrøði: ['persónurin, sum elskar alisfrøði','elskar alisfrøði']
    gammalt dýr: ['persónurin við einum kelidjóri, sum er gamalt fyri sítt slag',' hevur eitt kelidjór, sum er gamalt fyri sítt slag']
    skíðhopp: ['persónurin, sum hyggur at skíðhoppi.','hyggur at skíðhoppi']

red_herring_facts:
    sild: "sild er fiskur"
    sólskipaninar: "sólskipanin flytur seg við eini ferð á umleið 200 km/s um miðjuna á stjørnubreytini" 
    gáta: "tað er stuttligt at loysa gátur"
    hús: "øll húsini á vegnum hava snøggar garðar"
    hurðar: "fleiri av húsunum hava grøna hurðar"
    vindeygu: "øll húsini hava stór vindeygu"
    bilar: "tað eru nógvir bilar á vegnum"
    agurk: "ein agurk er eitt ber"
    snigil: "sniglar eru lindýr"
    kaffi: "kaffi inniheldur koffein"
