# Config file for generating zebra puzzles

# Possible combinations of languages and themes:
# da/huse
# da/smoerrebroed
# en/houses

defaults:
  - language: da/smoerrebroed
  - override hydra/job_logging: custom
  - _self_

# Model
# The LLM model to evaluate on the puzzles.
model : gpt-4o-mini

# Whether to generate new LLM responses or only evaluate existing ones when running evaluate.py
generate_new_responses: True

# Number of puzzles to generate
n_puzzles: 4

# Objects e.g. houses
n_objects: 3

# Attributes e.g. pets
n_attributes: 3

# Number of red herring clues generated
n_red_herring_clues: 5

# Number of red herrings clues evaluated
# This must be less than or equal to n_red_herring_clues, as clues can be removed but not added during evaluation.
n_red_herring_clues_evaluated: 3

# Weights for the clue types
clue_weights:
    found_at: 1
    not_at: 1
    next_to: 1
    not_next_to: 1
    just_left_of: 1
    just_right_of: 1
    left_of: 1
    right_of: 1
    same_object: 1
    not_same_object: 1
    between: 1
    not_between: 1
    multiple_between: 1
    one_between: 1
