# Config file for generating zebra puzzles

# Possible combinations of languages and themes:
# da/config_huse
# da/config_smoerrebroed
# eng/config_houses

defaults:
  - language: da/config_huse
  - override hydra/job_logging: custom
  - _self_

# Number of puzzles to generate
n_puzzles: 10

# Objects e.g. houses
n_objects: 2

# Attributes e.g. pets
n_attributes: 1
