# Config file for generating zebra puzzles in Danish with the classic "houses" theme.

# Time estimates per puzzle with all clues:
# 3x7: 0.7 s
# 4x4: 0.6 s
# 4x5: 16 s
# 4x6:
# 5x3: 3.8 s
# 6x3: >10 min

defaults:
  - override hydra/job_logging: custom
  - _self_

# Theme
theme: da_huse

# Model
# The LLM model to evaluate on the puzzles.
# examples: gpt-4o-mini, gpt-4o, o3-mini, o3
model : o3-mini

# Number of puzzles to generate
n_puzzles: 4

# Objects e.g. houses
# Currently, 2 - 7 are supported
n_objects: 3

# Attributes e.g. pets
# Currently, 2 - 7 are supported.
n_attributes: 7

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# TODO: Add support for multiple languages and themes by adding more config files.
# TODO: Make the phrasing sound more natural

attributes:

    land:
        Danmark: danskeren
        Sverige: svenskeren
        Letland: letteren
        Frankrig: franskmanden
        Spanien: spanieren
        Italien: italieneren
        Norge: nordmanden
        Fæøerne: færingen
        Nederlandene: nederlænderen
        Island: islænderen
        Storbritannien: briten

    hobby:
        klatring: personen der klatrer
        maling: personen der maler
        brætspil: personen der spiller brætspil
        tennis: personen der spiller tennis
        hækling: personen der hækler
        fodbold: personen der spiller fodbold
        håndbold: personen der spiller håndbold

    kæledyr:
        kat: katteejeren
        hund: hundeejeren
        kanin: kaninejeren
        zebra: zebraejeren
        undulat: undulatejeren
        snegl: snegleejeren
        vandrende pind: ejeren af en vandrende pind

    job:
        bager: bageren
        minister: ministeren
        politibetjent: politibetjenten
        sygeplejer: sygeplejeren
        lærer: læreren
        software developer: software developeren
        butiksassistent: butiksassistenten

    drik:
        juice: personen der drikker juice
        kaffe: personen der drikker kaffe
        mælk: personen der drikker mælk
        smoothie: personen der drikker smoothie
        kakao: personen der drikker kakao
        te: personen der drikker te
        sodavand: personen der drikker sodavand

    yndlingsfrugt:
        æble: personen der foretrækker æble
        pære: personen der foretrækker pære
        appelsin: personen der foretrækker appelsin
        banan: personen der foretrækker banan
        jordbær: personen der foretrækker jordbær
        solbær: personen der foretrækker solbær
        skovjordbær: personen der foretrækker skovjordbær

    yndlingsboggenre:
        faglitteratur: personen der læser faglitteratur
        krimi: personen der læser krimier
        fantasy: personen der læser fantasy
        science fiction: personen der læser science fiction
        gyser: personen der læser gysere
        poesi: personen der læser poesi
        kærlighedsromaner: personen der læser kærlighedsromaner


# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues: found_at, not_at
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: "{attribute_desc} bor i hus nummer {i_object}."
    not_at: "{attribute_desc} bor ikke i hus nummer {i_object}."
    next_to: "{attribute_desc_1} bor ved siden af {attribute_desc_2}."                                                             # Requires n_objects > 2, otherwise use not_same_object
    not_next_to: "{attribute_desc_1} bor ikke ved siden af {attribute_desc_2}, og de er ikke den samme person."                    # Requires n_objects > 2, otherwise it cannot be used
    just_left_of: "{attribute_desc_1} bor lige til venstre for {attribute_desc_2}."
    just_right_of: "{attribute_desc_1} bor lige til højre for {attribute_desc_2}."
    left_of: "{attribute_desc_1} bor til venstre for {attribute_desc_2}."                                                          # Requires n_objects > 2, otherwise use just_left_of
    right_of: "{attribute_desc_1} bor til højre for {attribute_desc_2}."                                                           # Requires n_objects > 2, otherwise use just_right_of
    same_object: "{attribute_desc_1} er {attribute_desc_2}."                                                                       # Requires n_attributes > 1, otherwise it cannot be used
    not_same_object: "{attribute_desc_1} er ikke {attribute_desc_2}."                                                              # Requires n_attributes > 1, otherwise it cannot be used
    between: "{attribute_desc_2} bor mellem {attribute_desc_1} og {attribute_desc_3}."                                             # Requires n_objects > 2, otherwise it cannot be used
    not_between: "{attribute_desc_1} bor ikke mellem {attribute_desc_2} og {attribute_desc_3}, og de er tre forskellige personer." # Requires n_objects > 2, otherwise it cannot be used
    n_between: "{attribute_desc_1} og {attribute_desc_2} bor med {n_between} huse mellem sig."                                     # Requires n_objects > 2, otherwise it cannot be used


# Prompt
# TODO: Support the grammar of puzzles with a single category

prompt_and: og

prompt_template: |
  En række huse er nummereret fra 1 til {n_objects} fra venstre mod højre.

  I hvert hus bor en person med unikke egenskaber i hver af de følgende kategorier:

  {chosen_attributes_str}

  Derudover ved vi følgende:

  {chosen_clues_str}

  Hvem har hvilke egenskaber og bor i hvilket hus?

  Angiv venligst dit svar som et JSON dictionary på nedenstående format. Hver række skal starte med object_X hvor X er husnummeret. Hver kolonne repræsenterer en kategori, og de skal stå i samme rækkefølge som kategorierne er listet ovenfor.

  {solution_template}
