# Config file for generating zebra puzzles in Danish with the classic "houses" theme.

# Time estimates per puzzle with all clues:
# 3x7: 0.7 s
# 4x4: 0.6 s
# 4x5: 16 s
# 4x6:
# 5x3: 3.8 s
# 6x3: >10 min

defaults:
  - override hydra/job_logging: custom
  - _self_


# Number of puzzles to generate
n_puzzles: 10

# Objects e.g. houses
# Currently, 2 - 7 are supported
n_objects: 3

# Attributes e.g. pets
# Currently, 2 - 7 are supported.
n_attributes: 7

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# The attributes below should be in the preferred order of categories in the clues.
# TODO: Add support for multiple languages and themes by adding more config files.
# TODO: Make the phrasing sound more natural

attributes:

    land:
        Danmark: ['danskeren', 'er dansk']
        Sverige: ['svenskeren', 'er svensk']
        Letland: ['letteren', 'er lettisk']
        Frankrig: ['franskmanden', 'er fransk']
        Spanien: ['spanieren', 'er spansk']
        Italien: ['italieneren', 'er italiensk']
        Norge: ['nordmanden', 'er norsk']
        Fæøerne: ['færingen', 'er færøsk']
        Nederlandene: ['nederlænderen', 'er nederlandsk']
        Island: ['islænderen', 'er islandsk']
        Storbritannien: ['briten', 'er britisk']

    job:
        bager: ['bageren', 'er bager']
        minister: ['ministeren', 'er minister']
        politibetjent: ['politibetjenten', 'er politibetjent']
        sygeplejerske: ['sygeplejersken', 'er sygeplejerske']
        lærer: ['læreren', 'er lærer']
        software developer: ['software developeren', 'er software developer']
        butiksassistent: ['butiksassistenten', 'er butiksassistent']

    kæledyr:
        kat: ['katteejeren','har en kat']
        hund: ['hundeejeren','har en hund']
        kanin: ['kaninejeren','har en kanin']
        zebra: ['zebraejeren','har en zebra']
        undulat: ['undulatejeren','har en undulat']
        snegl: ['snegleejeren','har en snegl']
        vandrende pind: ['ejeren af en vandrende pind','har en vandrende pind']

    drik:
        juice: ['juicedrikkeren', 'drikker juice']
        kaffe: ['kaffedrikkeren', 'drikker kaffe']
        mælk: ['mælkedrikkeren', 'drikker mælk']
        smoothie: ['smoothiedrikkeren', 'drikker smoothie']
        kakao: ['kakaodrikkeren', 'drikker kakao']
        te: ['tedrikkeren', 'drikker te']
        sodavand: ['sodavandsdrikkeren', 'drikker sodavand']

    yndlingsboggenre:
        faglitteratur: ['personen der læser faglitteratur', 'læser faglitteratur']
        krimi: ['krimilæseren', 'læser krimier']
        fantasy: ['fantasylæseren', 'læser fantasy']
        science fiction: ['personen der læser science fiction', 'læser science fiction']
        gyser: ['gyserlæseren', 'læser gysere']
        poesi: ['poesilæseren', 'læser poesi']
        kærlighedsromaner: ['personen der læser kærlighedsromaner', 'læser kærlighedsromaner']

    hobby:
        klatring: ['personen der klatrer', 'klatrer']
        maleri: ['personen der maler', 'maler']
        brætspil: ['personen der spiller brætspil', 'spiller brætspil']
        tennis: ['personen der spiller tennis', 'spiller tennis']
        hækling: ['personen der hækler', 'hækler']
        fodbold: ['personen der spiller fodbold', 'spiller fodbold']
        håndbold: ['personen der spiller håndbold', 'spiller håndbold']

    yndlingsfrugt:
        æble: ['personen der elsker æbler', 'elsker æbler']
        pære: ['personen der elsker pærer', 'elsker pærer']
        appelsin: ['personen der elsker appelsiner', 'elsker appelsiner']
        banan: ['personen der elsker bananer', 'elsker bananer']
        jordbær: ['personen der elsker jordbær', 'elsker jordbær']
        solbær: ['personen der elsker solbær', 'elsker solbær']
        skovjordbær: ['personen der elsker skovjordbær', 'elsker skovjordbær']



# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues: found_at, not_at
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: "{attribute_desc} bor i hus nummer {i_object}."
    not_at: "{attribute_desc} bor ikke i hus nummer {i_object}."
    next_to: "{attribute_desc_1} bor ved siden af {attribute_desc_2}."                                                             # Requires n_objects > 2, otherwise use not_same_object
    not_next_to: "{attribute_desc_1} bor ikke ved siden af {attribute_desc_2}, og de er ikke den samme person."                    # Requires n_objects > 2, otherwise it cannot be used
    just_left_of: "{attribute_desc_1} bor lige til venstre for {attribute_desc_2}."
    just_right_of: "{attribute_desc_1} bor lige til højre for {attribute_desc_2}."
    left_of: "{attribute_desc_1} bor til venstre for {attribute_desc_2}."                                                          # Requires n_objects > 2, otherwise use just_left_of
    right_of: "{attribute_desc_1} bor til højre for {attribute_desc_2}."                                                           # Requires n_objects > 2, otherwise use just_right_of
    same_object: "{attribute_desc_1} {attribute_desc_2}."                                                                          # Requires n_attributes > 1, otherwise it cannot be used
    not_same_object: "{attribute_desc_1} {attribute_desc_2}."                                                                      # Requires n_attributes > 1, otherwise it cannot be used
    between: "{attribute_desc_2} bor mellem {attribute_desc_1} og {attribute_desc_3}."                                             # Requires n_objects > 2, otherwise it cannot be used
    not_between: "{attribute_desc_1} bor ikke mellem {attribute_desc_2} og {attribute_desc_3}, og de er tre forskellige personer." # Requires n_objects > 2, otherwise it cannot be used
    n_between: "{attribute_desc_1} og {attribute_desc_2} bor med {n_between} huse mellem sig."                                     # Requires n_objects > 2, otherwise it cannot be used


# Prompt
# TODO: Support the grammar of puzzles with a single category

prompt_and: og
prompt_not: ikke

prompt_template: |
  En række huse er nummereret fra 1 til {n_objects} fra venstre mod højre.

  I hvert hus bor en person med unikke egenskaber i hver af de følgende kategorier:

  {chosen_attributes_str}

  Derudover ved vi følgende:

  {chosen_clues_str}

  Hvem har hvilke egenskaber og bor i hvilket hus? Angiv dit svar i følgende format, hvor det første tal i hver række repræsenterer husnummeret:

  1, egenskab_1, egenskab_2, egenskab_3 ...
  2, egenskab_1, egenskab_2, egenskab_3 ...
  ...
