# Config file for generating zebra puzzles

# Possible combinations of languages and themes:
# da/huse
# da/smoerrebroed
# en/houses

defaults:
  - language: da/smoerrebroed
  - override hydra/job_logging: custom
  - _self_

# Model
# The LLM model to evaluate on the puzzles.
model : gpt-4o-mini

# Whether to generate new LLM responses or only evaluate existing ones when running evaluate.py
generate_new_responses: False

# Number of puzzles to generate
n_puzzles: 4

# Objects e.g. houses
n_objects: 4

# Attributes e.g. pets
n_attributes: 4
