# Config file for generating zebra puzzles

# Possible combinations of languages and themes:
# da/huse
# da/smoerrebroed
# en/houses

defaults:
  - language: da/huse
  - override hydra/job_logging: custom
  - _self_

# Number of puzzles to generate
n_puzzles: 1

# Objects e.g. houses
n_objects: 3

# Attributes e.g. pets
n_attributes: 4
