# Config file for generating zebra puzzles in Danish with the classic "houses" theme.

#Time estimates per puzzle:
# 3x5: 0.1 s
# 3x6: 0.5 s
# 3x7: 2.6 s
# 4x4: 3.5 s
# 5x3: 12 s
# 4x5: 2 min
# 6x3: >10 min

defaults:
  - override hydra/job_logging: custom
  - _self_


# Number of puzzles to generate
n_puzzles: 10

# Objects e.g. houses
# Currently, 2 - 7 are supported
n_objects: 4

# Attributes e.g. pets
# Currently, 2 - 7 are supported
n_attributes: 2

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# In Danish, the attribute description completes the phrase "Personen der...".
# TODO: Add support for multiple languages and themes by adding more config files.
# TODO: Make the phrasing sound more natural

attributes:
    land:
        Danmark: er fra Danmark
        Sverige: er fra Sverige
        Letland: er fra Letland
        Frankrig: er fra Frankrig
        Spanien: er fra Spanien
        Kina: er fra Kina
        Chile: er fra Chile

    hobby:
        klatring: klatrer
        maling: maler
        brætspil: spiller brætspil
        tennis: spiller tennis
        hækling: hækler
        fodbold: spiller fodbold
        håndbold: spiller håndbold

    kæledyr:
        kat: har en kat
        hund: har en hund
        kanin: har en kanin
        zebra: har en zebra
        undulat: har en undulat
        snegl: har en snegl
        vandrende pind: har en vandrende pind

    job:
        bager: er bager
        minister: er minister
        politibetjent: er politibetjent
        sygeplejer: er sygeplejer
        lærer: er lærer
        software developer: er software developer
        butiksassistent: er butiksassistent

    drik:
        juice: drikker juice
        kaffe: drikker kaffe
        mælk: drikker mælk
        smoothie: drikker smoothie
        kakao: drikker kakao
        te: drikker te
        sodavand: drikker sodavand

    yndlingsfrugt:
        æble: foretrækker æble
        pære: foretrækker pære
        appelsin: foretrækker appelsin
        banan: foretrækker banan
        jordbær: foretrækker jordbær
        solbær: foretrækker solbær
        skovjordbær: foretrækker skovjordbær

    yndlingsgenre:
        faglitteratur: læser faglitteratur
        krimi: læser krimier
        fantasy: læser fantasy
        science fiction: læser science fiction
        gyser: læser gysere
        poesi: læser poesi
        kærlighedsromaner: læser kærlighedsromaner



# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues: found_at, not_at
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: Personen der {attribute_desc} bor i hus nummer {i_object}.
    not_at: Personen der {attribute_desc} bor ikke i hus nummer {i_other_object}.
    next_to: Personen der {attribute_desc_1} bor ved siden af personen der {attribute_desc_2}.


#Prompt
# TODO: Improve the prompt incl. by adding a description of the desired format of the response.
# TODO: Support the grammar of puzzles with a single category and/or object

prompt_template: |
  Her følger en opgave.

  Der er {n_objects} huse på en række. I hvert hus bor en person med en bestemte egenskaber, som er forskellige fra de andre.

  Du skal gætte egenskaber fra kategorierne {chosen_categories_part1} og {chosen_categories_part2} for hver person. De mulige egenskaber er {chosen_attributes_part1} og {chosen_attributes_part2}. Her følger et eller flere hints:

  {chosen_clues_str}

  Hvem har hvilke egenskaber og bor i hvilket hus?
