# Config file for generating zebra puzzles in Danish with the "smørrebrød" theme.

defaults:
  - override hydra/job_logging: custom
  - _self_


# Number of puzzles to generate
n_puzzles: 10

# Objects e.g. houses
# Currently, 2 - 8 are supported
n_objects: 3

# Attributes e.g. pets
# Currently, 2 - 6 are supported.
n_attributes: 5

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# The attributes below should be in the preferred order of categories in the clues.

attributes:

    brød:
        softkernerugbrød: ['stykket med softkernerugbrød', 'er med softkernerugbrød']
        solsikkerugbrød: ['stykket med solsikkerugbrød', 'er med solsikkerugbrød']
        vesterhavsrugbrød: ['stykket med vesterhavsrugbrød', 'er med vesterhavsrugbrød']
        sønderjysk rugbrød: ['stykket med sønderjysk rugbrød', 'er med sønderjysk rugbrød']
        glutenfrit rugbrød: ['stykket med glutenfrit rugbrød', 'er med glutenfrit rugbrød']
        franskbrød: ['stykket med franskbrød', 'er med franskbrød']
        groft landbrød: ['stykket med groft landbrød', 'er med groft landbrød']
        ristet rugbrød: ['stykket med ristet rugbrød', 'er med ristet rugbrød']

    smørelse:
        smør: ['stykket med smør', 'er smurt med smør']
        andefedt: ['stykket med andefedt', 'er smurt med andefedt']
        svinefedt: ['stykket med svinefedt', 'er smurt med svinefedt']
        plantesmør: ['stykket med plantesmør', 'er smurt med plantesmør']
        flødeost: ['stykket med flødeost', 'er smurt med flødeost']
        hummus: ['stykket med hummus', 'er smurt med hummus']
        pesto: ['stykket med pesto', 'er smurt med pesto']
        mayonnaise: ['stykket med mayonnaise', 'er smurt med mayonnaise']

    pålæg:
        røget laks: ['stykket med røget laks', 'er med røget laks']
        roastbeef: ['stykket med roastbeef', 'er med roastbeef']
        spegepølse: ['stykket med spegepølse', 'er med spegepølse']
        leverpostej: ['stykket med leverpostej', 'er med leverpostej']
        kartoffel: ['stykket med kartoffel', 'er med kartoffel']
        sild: ['stykket med sild', 'er med sild']
        avocado: ['stykket med avocado', 'er med avocado']
        rejer: ['stykket med rejer', 'er med rejer']
        fiskefilet:
            - stykket med fiskefilet
            - er med fiskefilet

    sekundært pålæg:
        æg: ['stykket med æg', 'er med æg']
        ost: ['stykket med ost', 'er med ost']
        asparges: ['stykket med asparges', 'er med asparges']
        tomat: ['stykket med tomat', 'er med tomat']
        agurk: ['stykket med agurk', 'er med agurk']
        rødløg: ['stykket med rødløg', 'er med rødløg']
        bacon: ['stykket med bacon', 'er med bacon']
        stegte svampe: ['stykket med stegte svampe', 'er med stegte svampe']
        sky: ['stykket med sky', 'er med sky']
        rødbede: ['stykket med rødbede', 'er med rødbede']

    pynt:
        radise: ['stykket med radise', 'er pyntet med radise']
        karse: ['stykket med karse', 'er pyntet med karse]gt']
        syltede agurker: ['stykket med syltede agurker', 'er pyntet med syltede agurker']
        kørvel: ['stykket med kørvel', 'er pyntet med kørvel']
        purløg: ['stykket med purløg', 'er pyntet med purløg']
        peberrod: ['stykket med peberrod', 'er pyntet med peberrod']
        citronskiver: ['stykket med citronskiver', 'er pyntet med citronskiver']
        remoulade: ['stykket med remoulade', 'er pyntet med remoulade']
        dild: ['stykket med dild', 'er pyntet med dild']
        kaviar: ['stykket med kaviar', 'er pyntet med kaviar']

    drys:
        flagesalt: ['stykket med flagesalt', 'er drysset med flagesalt']
        peber: ['stykket med peber', 'er drysset med peber']
        sesamfrø: ['stykket med sesamfrø', 'er drysset med sesamfrø']
        ristede løg: ['stykket med ristede løg', 'er drysset med ristede løg']
        chiliflager: ['stykket med chiliflager', 'er drysset med chiliflager']
        spidskommen: ['stykket med spidskommen', 'er drysset med spidskommen']
        ristede mandler: ['stykket med ristede mandler', 'er drysset med ristede mandler']
        ingenting: ['stykket uden drys', 'er uden drys']


# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues: found_at, not_at
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: "{attribute_desc} er nummer {i_object}."
    not_at: "{attribute_desc} er ikke nummer {i_object}."
    next_to: "{attribute_desc_1} ligger ved siden af {attribute_desc_2}."                                                                       # Requires n_objects > 2, otherwise use not_same_object
    not_next_to: "{attribute_desc_1} ligger ikke ved siden af {attribute_desc_2}, og de er ikke den samme person."                              # Requires n_objects > 2, otherwise it cannot be used
    just_left_of: "{attribute_desc_1} ligger lige til venstre for {attribute_desc_2}."
    just_right_of: "{attribute_desc_1} ligger lige til højre for {attribute_desc_2}."
    left_of: "{attribute_desc_1} ligger til venstre for {attribute_desc_2}."                                                                    # Requires n_objects > 2, otherwise use just_left_of
    right_of: "{attribute_desc_1} ligger til højre for {attribute_desc_2}."                                                                     # Requires n_objects > 2, otherwise use just_right_of
    same_object: "{attribute_desc_1} {attribute_desc_2}."                                                                                       # Requires n_attributes > 1, otherwise it cannot be used
    not_same_object: "{attribute_desc_1} {attribute_desc_2}."                                                                                   # Requires n_attributes > 1, otherwise it cannot be used
    between: "{attribute_desc_2} ligger mellem {attribute_desc_1} og {attribute_desc_3}."                                                       # Requires n_objects > 2, otherwise it cannot be used
    not_between: "{attribute_desc_1} ligger ikke mellem {attribute_desc_2} og {attribute_desc_3}, og de er tre forskellige stykker smørrebrød." # Requires n_objects > 2, otherwise it cannot be used
    n_between: "{attribute_desc_1} og {attribute_desc_2} ligger med {n_between} stykker smørrebrød mellem sig."                                 # Requires n_objects > 2, otherwise it cannot be used


# Prompt
# TODO: Support the grammar of puzzles with a single category

prompt_and: og
prompt_not: ikke

prompt_template: |
  {n_objects} kokke præsenterer hvert deres stykke smørrebrød. Stykkerne ligger på række og er nummereret fra 1 til {n_objects} fra venstre mod højre.

  Hvert stykke har unikke egenskaber i hver af de følgende kategorier:

  {chosen_attributes_str}

  Derudover ved vi følgende:

  {chosen_clues_str}

  Hvilke ingredienser indgår i hvilke smørrebrød? Angiv dit svar i følgende format, hvor det første tal i hver række angiver smørrebrødets nummer:

  1, egenskab_1, egenskab_2, egenskab_3 ...
  2, egenskab_1, egenskab_2, egenskab_3 ...
  ...
