# Config file for generating zebra puzzles in Danish with the classic "houses" theme.

# Time estimates per puzzle with found_at and not_at:
# 3x5: 0.1 s
# 3x6: 0.5 s
# 3x7: 2.6 s
# 4x4: 3.5 s
# 5x3: 12 s
# 4x5: 2 min
# 6x3: >10 min

# Time estimates per puzzle with all clues:
# 3x6: 0.3 s
# 3x7: 1.6 s
# 4x4: 1.6 s
# 4x5: 1.4 min
# 5x3: 9.2 s

defaults:
  - override hydra/job_logging: custom
  - _self_


# Number of puzzles to generate
n_puzzles: 10

# Objects e.g. houses
# Currently, 2 - 7 are supported
n_objects: 3

# Attributes e.g. pets
# Currently, 2 - 7 are supported.
n_attributes: 2

# Attributes
# The attributes are defined as a dictionary of dictionaries.
# The outer dictionary has the attribute category as key, and the inner dictionary has the attribute value as key and the attribute description as value.
# In Danish, the attribute description completes the phrase "Personen der...".
# TODO: Add support for multiple languages and themes by adding more config files.
# TODO: Make the phrasing sound more natural

attributes:
    land:
        Danmark: danskeren
        Sverige: svenskeren
        Letland: letteren
        Frankrig: franskmanden
        Spanien: spanieren
        Italien: italieneren
        Norge: nordmanden
        Fæøerne: færingen
        Nederlandene: nederlænderen
        Island: islænderen
        Storbritannien: briten

    hobby:
        klatring: personen der klatrer
        maling: personen der maler
        brætspil: personen der spiller brætspil
        tennis: personen der spiller tennis
        hækling: personen der hækler
        fodbold: personen der spiller fodbold
        håndbold: personen der spiller håndbold

    kæledyr:
        kat: katteejeren
        hund: hundeejeren
        kanin: kaninejeren
        zebra: zebraejeren
        undulat: undulatejeren
        snegl: snegleejeren
        vandrende pind: ejeren af en vandrende pind

    job:
        bager: bageren
        minister: ministeren
        politibetjent: politibetjenten
        sygeplejer: sygeplejeren
        lærer: læreren
        software developer: software developeren
        butiksassistent: butiksassistenten

    drik:
        juice: personen der drikker juice
        kaffe: personen der drikker kaffe
        mælk: personen der drikker mælk
        smoothie: personen der drikker smoothie
        kakao: personen der drikker kakao
        te: personen der drikker te
        sodavand: personen der drikker sodavand

    yndlingsfrugt:
        æble: personen der foretrækker æble
        pære: personen der foretrækker pære
        appelsin: personen der foretrækker appelsin
        banan: personen der foretrækker banan
        jordbær: personen der foretrækker jordbær
        solbær: personen der foretrækker solbær
        skovjordbær: personen der foretrækker skovjordbær

    yndlingsgenre:
        faglitteratur: personen der læser faglitteratur
        krimi: personen der læser krimier
        fantasy: personen der læser fantasy
        science fiction: personen der læser science fiction
        gyser: personen der læser gysere
        poesi: personen der læser poesi
        kærlighedsromaner: personen der læser kærlighedsromaner



# Clues
# Clue names and text for the prompt depending on the clue type.
# Clue names should not be edited, but they can be a subset of the full list of implemented clues: found_at, not_at
# NOTE: The list of clues could be extended by adding non-unique attributes, superattributes (e.g. large animal), ordinal attributes, objects on a grid etc.
clues_dict:
    found_at: "{attribute_desc} bor i hus nummer {i_object}."
    not_at: "{attribute_desc} bor ikke i hus nummer {i_other_object}."
    next_to: "{attribute_desc_1} bor ved siden af {attribute_desc_2}."                          # Requires n_objects > 2, otherwise use not_same_object
    not_next_to: "{attribute_desc_1} bor ikke ved siden af {attribute_desc_2}."                 # Requires n_objects > 2, otherwise it cannot be used
    just_left_of: "{attribute_desc_1} bor lige til venstre for {attribute_desc_2}."
    just_right_of: "{attribute_desc_1} bor lige til højre for {attribute_desc_2}."
    left_of: "{attribute_desc_1} bor til venstre for {attribute_desc_2}."                       # Requires n_objects > 2, otherwise use just_left_of
    right_of: "{attribute_desc_1} bor til højre for {attribute_desc_2}."                        # Requires n_objects > 2, otherwise use just_right_of
    same_object: "{attribute_desc_1} er {attribute_desc_2}."                                    # Requires n_attributes > 1, otherwise it cannot be used
    not_same_object: "{attribute_desc_1} er ikke {attribute_desc_2}."                           # Requires n_attributes > 1, otherwise it cannot be used
    between: "{attribute_desc_2} bor mellem {attribute_desc_1} og {attribute_desc_3}."          # Requires n_objects > 2, otherwise it cannot be used
    not_between: "{attribute_desc_1} bor ikke mellem {attribute_desc_2} og {attribute_desc_3}." # Requires n_objects > 2, otherwise it cannot be used
    n_between: "{attribute_desc_1} og {attribute_desc_2} bor med {n_between} huse mellem sig."   # Requires n_objects > 2, otherwise it cannot be used


# Prompt
# TODO: Support the grammar of puzzles with a single category

prompt_template: |
  En række huse er nummereret fra 1 til {n_objects} fra venstre mod højre. I hvert hus bor en person med en bestemte egenskaber, som er forskellige fra de andre.

  Du skal gætte egenskaber fra kategorierne {chosen_categories_part1} og {chosen_categories_part2} for hver person. De mulige egenskaber er {chosen_attributes_part1} og {chosen_attributes_part2}.

  Her følger et eller flere hints:

  {chosen_clues_str}

  Hvem har hvilke egenskaber og bor i hvilket hus? Angiv dit svar i følgende format, hvor det første tal i hver række repræsenterer husnummeret:

  1, egenskab_1, egenskab_2, egenskab_3 ...
  2, egenskab_1, egenskab_2, egenskab_3 ...
  ...
