# Config file for generating zebra puzzles

# Possible combinations of languages and themes:
# da/huse
# da/smoerrebroed
# en/houses

defaults:
  - language: da/smoerrebroed
  - override hydra/job_logging: custom
  - _self_

# Theme
theme: da_huse

# Model
# The LLM model to evaluate on the puzzles.
# examples: gpt-4o-mini, gpt-4o, o3-mini, o3
model : gpt-4o-mini

# Number of puzzles to generate
n_puzzles: 2

# Objects e.g. houses
n_objects: 3

# Attributes e.g. pets
n_attributes: 4
